### PR TITLE
Lazy loading of XML files (#20)

### PR DESCRIPTION
**Pull request by felipenoris**
This will improve performance as described in #20 .

### CODE REVIEW

**Comment by felipenoris** [comment]
@rjplevin, results are promising:

```julia
println("ExcelReaders")
@time dice2010_excel_parameters(useXLSX=false);

println("XLSX")
@time dice2010_excel_parameters(useXLSX=true);
```

Outputs this after warmup:

```
ExcelReaders
  0.761371 seconds (48.37 k allocations: 1.662 MiB)
XLSX
  0.583686 seconds (6.82 M allocations: 213.925 MiB, 4.44% gc time)
```

There's a new function `XLSX.openxlsx` that will load XML files lazily.
To use it, I had to change this line in your script:

```julia
# Open DICE_2010 Excel file to read parameters
 f = useXLSX ? XLSX.openxlsx(filename) : openxl(filename)
```

**Comment by rjplevin** [comment]
That looks great! I look forward to trying it out.

**Comment by felipenoris** [comment]
Don't worry.. I'll merge it tomorrow. There's one more optimisation that I'll do before merging.

**Comment by felipenoris** [comment]
A slight improvement on lazy-loading shared strings table. In your case you don't get any strings, so now the package does not load the SST.

```
ExcelReaders
  0.770031 seconds (48.37 k allocations: 1.662 MiB)
XLSX
  0.561451 seconds (6.63 M allocations: 208.159 MiB, 4.28% gc time)
```

**Comment by rjplevin** [comment]
Nice job. On my Mac, XLSX is still slower than ExcelReader, but not by much:
```
Main> @time begin dice2010_excel_parameters(datafile, useXLSX=true); nothing end
  1.036118 seconds (6.63 M allocations: 208.159 MiB, 1.93% gc time)

Main> @time begin dice2010_excel_parameters(datafile, useXLSX=false); nothing end
  0.588993 seconds (48.38 k allocations: 1.662 MiB)
```
I'm puzzled at why the performance ordering is reversed on our machines.

I ran the profiler on this function. It looks like the bottleneck is `EzXML.readxml()`, which makes sense, and within that, calls ZipFile's io functions. Given that, the way to gain further speed would appear to be to read less of the XML.

**Pull request merged**
