### PR TITLE
WIP: DataStreams integration

### PR DESCRIPTION
**Pull request by quinnj**
Here's a start, a couple thoughts as I was going thru this:

* I wasn't sure exactly how to get at the table data in a `Worksheet`, but I tried to follow examples and use the worksheet.jl file for reference
* Ideally, we'd have a way to allow the user to specify column headers if they exist in the worksheet (this implementation just streams all data as data)
* If their data doesn't start at A1, can we still use `CellRef`? Ideally, we'd have a way to say, "give me the cell value for row 3, column 4, relative to wherever my datagrid starts on a worksheet". Maybe that already exists?
* Am I right in assuming that cells support random access? (i.e. you can jump to any cell w/o needing to process cells in between). From perusing the code, it seemed so.

### CODE REVIEW

**Comment by felipenoris** [comment]
You can ask any cell with random access. It will just return `Missings.missing` if the cell is empty.

If you ask for all the data without specifying a range (as in `sheet[:]` or `XLSX.getdata(sheet)`), the function will return `sheet[XLSX.dimension(sheet)]`, which is a Worksheet property that says the full range of the worksheet. Sometimes it doesn´t work well depending on how the Excel file was generated (or maybe the user edited some cell in a random location and the Excel application didn´t do a clean up).

Looking at the current implementation, you´ll run into some performance problems to stream data. I´m working today on a row iterator that will be useful for DataStreams integration. Just give me a few hours and I´ll commit it.

**Comment by felipenoris** [comment]
`If their data doesn't start at A1, can we still use CellRef?`
Yes. It will return `Missings.missing` if you ask for an empty cell. But currently you have to specify a `CellRef` to get data. I´ll add a function to query based on `[row, column, anchor]`, where `anchor` is a `CellRef` and `row`, `column` will be relative to that anchor.

**Comment by felipenoris** [comment]
Just ran a benchmark against ExcelReaders.jl . This package is about 20x faster.

**Comment by felipenoris** [comment]
@quinnj , now that `gettable` is stable, I think you can just use the result of this method to implement the DataStreams integration. Check que docstring for `gettable` and the `infer_eltypes` option.

The drawback of this implementation is that the full table will be in memory. For now this won't make much difference until I get to implement #3. Once that's done I'll refactor the DataStreams integration to use `TableRowIterator` instead of `gettable` method.

**Comment by quinnj** [comment]
Closing in favor of #58

**Pull request closed without merging**
