### PR TITLE
Update read.jl to pass through Custom XML internal files

### PR DESCRIPTION
**Pull request by TimG1964**
Addresses issue #210

Simple change to `read.jl` to pass through Custom XML internal files in the same way as binary files are already passed through instead of simply ignoring them. As Issue #210 points out, when they are ignored during read, their absence causes an assertion error during write.

Discussion on Discourse [here](https://discourse.julialang.org/t/xlsx-jl-cannot-handle-customxml-elements-correctly-when-opening-files-as-templates/115778).

### CODE REVIEW

**Comment by TimG1964** [comment]
I've now added an example .xlsx file that contains customXml internal files. I don't think any of the existing examples contain these internal files. In my example, these elements were not added on purpose by the user but were created by Excel itself in the normal use of the application. I don't know their purpose or function but just acknowledge their presence.

I've also added a test to the test suite to read/write this customXml.xls file as a template. In the current master release, this test will fail, replicating issue #210. With my proposed code change, the test will pass.

**Comment by felipenoris** [comment]
Awesome! Thanks!

**Comment by TimG1964** [comment]
@felipenoris Could you make a new release for this, please?

**Comment by TimG1964** [comment]
Thank you!

**Pull request merged**
