### PR TITLE
use Parsers package for numeric parsing

### PR DESCRIPTION
**Pull request by chris-b1**
I've got a few performance related refactorings I'm playing with.  This one is relatively small impact (~10%), but also pretty simple as long as you're comfortable with taking [`Parsers.jl`](https://github.com/JuliaData/Parsers.jl) as a dependency

### CODE REVIEW

**Comment by felipenoris** [comment]
Ok, thanks!

**Comment by felipenoris** [comment]
@chris-b1 , sorry, I had to revert your contribution because I found a fundamental issue with Parsers:

```julia
julia> Parsers.tryparse(Int, "10.2")
10
```

I would need this to return `nothing` with a fail. If I parse `10.2` as `10` I lose information.

**Comment by felipenoris** [comment]
Ref https://github.com/JuliaData/Parsers.jl/issues/55

**Comment by chris-b1** [comment]
Ah, yes, this will need some more work.  In most places looks like I should be using `xparse`, it gives a return code (`0` means success) that can be used to trap invalid parses.

```julia
julia> val, code = Parsers.xparse(Int, "10.1")
(10, -32607, 1, 4, 4)

julia> Parsers.codes(-32607)
"INVALID: OK | EOF | INVALID_DELIMITER " 
```

**Pull request merged**
