### PR TITLE
Support Tables.jl interface w/ TableRowIterator

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
@felipenoris, [Tables.jl](https://github.com/JuliaData/Tables.jl) is the new hotness, so I wanted to take another stab (instead of #1 ) at integrating. Couple of things:
* yes, the interface really is that easy to satisfy; it's pretty great
* How do you feel about defining `Base.getproperty` on the `TableRow` type? It makes it a bit awkward in the rest of the code because of the `getfield(r, :symbol)`, but it could also be nice for users if they're iterating a sheet by themselves, i.e. to do `row.columnA` and get that value. Currently, whatever a "table" iterates needs to be "property-accessible"; i.e. be able to call `propertynames(row)` and then `getproperty(row, name)` for each name.

Anyway, take a look and I can add some tests.

**Comment by davidanthoff** [comment]
Could we put this into a separate package? We are in the process of taking a dependency on this package here for ExcelFiles.jl, but I don't want to take a dependency on Tables.jl.

@quinnj I think we discussed this at juliacon, right? That we would try to generally go for a design where the low-level file format packages like ExcelReaders, TextParse, ReadStat etc. don't take a dependency on either Tables, TableTraits or FileIO or stuff like that, so that one can use them without having to take a dependency on either of those package families.

**Comment by felipenoris** [comment]
Sorry about the delay. I'm going to add this dependency. I just need to do some benchmarks. I'll do it on this weekend.

**Comment by davidanthoff** [comment]
Note that I'm not suggesting that there shouldn't be a package that has integration between XLSX.jl and Tables.jl. What I'm suggesting is that we have something like XLSXLib.jl that has not dependency on Tables.jl and then say XLSX.jl that provides the Tables.jl integration. That model has worked really well for a number of other file IO packages I maintain (FeatherFiles.jl and FeatherLib.jl, ExcelFiles.jl and ExcelReaders.jl, CSVFiles.jl and TextParse.jl, StatFiles.jl and ReadStat.jl).

There is a use-case for packages that want to take a dependency on the functionality here but don't want to take a dependency on Tables.jl. Queryverse is one (and in fact we are one PR merge short of taking a dep on XLSX.jl), but I can also imagine more specialized situations where that is the case (we have e.g. one internal, entirely non-data related project where that would also be useful). My suggestion here would allow us to accommodate that requirement, and at the same time to share code, and have Tables.jl integration.

Obviously this is @felipenoris call. If this package here does take a dependency on Tables.jl, we would create a fork for the Queryverse use-case.

**Comment by quinnj** [comment]
@davidanthoff, could you comment more on why it's so undesirable to take a dependency on Tables.jl? As I mentioned, it's the complete opposite of a package like DataFrames, which has thousands of lines of codes, several poorly maintained dependencies, plus one dependency with a binary dependency. Tables.jl is a couple hundred lines at best, pure Julia, includes Requires.jl as the single, light, well maintained dependency, and has very few exports (for potential conflicts). It's pretty much the ideal dependency as an "interface" package that is super light for a package to depend on, yet provides a huge range of automatic integrations.

It seems unfair to ask @felipenoris to do a lot more work maintaining multiple packages, just to split out a very light dependency, especially when you haven't really explained why it would be such a problem for your packages to then take on as a dependency.

 > If this package here does take a dependency on Tables.jl, we would create a fork for the Queryverse use-case.

A while ago on slack, you asked why people weren't considering using/adapting TableTraits.jl for this new interest in a common table interface; I responded that one of my biggest hesitations was uncertainty with how collaborative you'd be if a bunch of us "data package" developers tried to work together. Comments like this ^^ seem to confirm my hesitation; "threatening" to fork any package that doesn't follow what you want isn't healthy for the data package ecosystem; it creates nearly identical packages that then create a sub-par experience for users as they now have to do extra research to learn about the difference between a world where packages like XLSX.jl, XLSXLib.jl, XLSXTables.jl, ExcelFiles.jl, etc. all exist. 

Please, let's collaborate! Let's communicate concerns and objections and work to find common ground and compromises that work for everyone instead of "drawing lines" in the ecosystem. It benefits end users and it benefits us all as we reduce duplicate engineer efforts.

**Comment by quinnj** [comment]
@felipenoris, I went ahead and added "sink" integration as well; it was pretty easy thanks to how well the `writetable` methods are organized. I also added some tests for read/write.

**Comment by felipenoris** [comment]
These are some interesting points. I also have the same concerns that @davidanthoff points out since the beginning of this discussion, regarding stability of **Tables.jl**. But as long as the *public API* of this package does not expose any data structure that is specific to **Tables.jl** I wouldn't mind taking the dependency:

* if something related to **Tables.jl** breaks, in the worst case scenario I could wipe out its code and my API would remain the same.

* if someone is relying on **Tables.jl** to do some integration with this package and everything breaks, well, that person agreed to use an *unstable* package in the first place.

I don't think that these scenarios are likely to happen. But, hey, we break things and come up with new ideas. That's how we got here, using Julia since version 0.3 or so.

About the **Requires** thing. In which scenarios this could break things? 

```
@require CategoricalArrays="324d7699-5711-5eae-9e2f-1d82baa6b597" begin
...
end
```

**Comment by quinnj** [comment]
The concern about Tables.jl being new is certainly valid. Here are my best arguments in favor of its current stability though:
* There have been no API changes since the 0.1.2 release, which was the first "real" release by means of other packages actually being able to take a dependency on it. Each of the 7 releases since then have only been performance or bug fixes, usually as a single commit. I've seen this as extremely positive: there are now some half-dozen packages w/ Tables.jl as a dependency, a few bugs have been discovered and quickly fixed, with corresponding releases to ensure a quick shake-out of bugs and smooth transition.

> I'm not convinced that it has a design that will allow it to never have a breaking change

It seems you have something specific in mind about the design in making this comment? Care to expound? I'd certainly like to hear about these kinds of issues/cases if you think they're so serious. In my mind, this is an easy issue: **don't making breaking changes**. Period. As an interface package, I think it's clear that Tables.jl is committing to the current interfaces as-is and any new or changing functionality will need to be additive and not change things as they currently work. Fortunately, the package has been designed with this in mind with the existence of the `Tables.rowaccess` and `Tables.columnaccess` functions to signal that a type implements a specific access pattern interface. If a new access pattern comes along, the existing interfaces will be untouched, and we'll just add something like `Tables.mostawesomeaccess` that types can then implement and start using if desired. 

> (without a proven track record of not breaking things)

Let's take the approach of "innocent until proven guilty" shall we? As mentioned above, there haven't been any breaking changes in the package so far, with none planned.

> I dealt with this problem for about 1.5 years in IterableTables.jl, and it was tricky, to say the least (and the situation was probably easier there than it is in Tables.jl).

I disagree on this point. The use of `@require` in Tables.jl is very limited; for CategoricalArrays & WeakRefStrings, it is to provide an internal interface implementation using basic, exported functionality of these packages. For DataValues, it provides some helper method overrides for Queryverse integration. I think the situation is very different than IterableTables.jl, which was providing _the actual interface implementations_ of a dozen or so packages. I think there's a big difference between using Requires.jl for low-level, infrequently changing, "foundational", "helper", or upstream packages vs. the IterableTables.jl situation, which included _downstream_ dependencies via Requires.jl.

**Comment by quinnj** [comment]
Bump.

**Comment by davidanthoff** [comment]
Still the same situation on my end: I don't want to take a dependency on Tables.jl in the Queryverse.jl, and we already have a dependency on XLSX.jl in ExcelFiles.jl, so if this gets merged we (Queryverse end of things) would probably have to fork this package here to avoid the dependency on Tables.jl. I would _really_ like to avoid that.

Let me also just stress again that I am _not_ trying to prevent a good XLSX lib for the Tables.jl ecosystem, I'm purely suggesting that it is done in a different package so that it doesn't disrupt other ecosystems that have different constraints/priorities and that have taken a dependency on this package here in its current state.

Just as another FYI, we plan to move ExcelFiles.jl to use XLSX.jl for reading of files as well (right now it just uses it for writing of files). I would assume that at that point any Tables.jl source/sink would also just have access to read/write functionality via XLSX.jl powered ExcelFiles.jl, right?

**Comment by davidanthoff** [comment]
Btw., would it be enough for the read case if `readtable` returned a named tuple of column vectors to make it a Tables.jl source? Without even taking a dep on Tables.jl?

**Comment by felipenoris** [comment]
I'll add a dep on `Requires.jl` for `XLSX.jl`, and then I'll load code conditional on `Tables.jl` and `DataFrames.jl`.

**Comment by nalimilan** [comment]
I don't think it makes sense to conditionally depend on DataFrames.jl via Requires.jl: either you need to depend on it unconditionally so that you can return a `DataFrame`, or just implement the Tables.jl interface as in this PR and `DataFrame(XLSX.readtable(...))` will work automatically without any additional dependency.

**Comment by felipenoris** [comment]
@nalimilan, you're right on your reasoning and I agree with you, but I'll experiment the conditional dep on DataFrames just for the `writetable` API. If Tables.jl is able to replace this functionality as well, then there will be no need for a dep on DataFrames.

**Comment by nalimilan** [comment]
OK. AFAICT Tables.jl also works for that use case, using the implementation from this PR.

**Comment by quinnj** [comment]
Bump; I think this would be really great to have. I think all of the original concerns are effectively moot at this point: Tables.jl has been stable pretty much from the beginning in terms of public API (almost 2 years now); the 1.0 release updated with additional Tables.jl-specific functions you _can_ overload if you don't want to overload getproperty/propertynames, but those are still fine and this PR should be good to go. We also now have more than [70 package integrations](https://juliahub.com/ui/Packages/Tables/Z804B/1.0.4), so rest assured nothing will be breaking/changing any time soon.

I'll resolve the merge conflicts here if you want to take a look again.

**Comment by quinnj** [comment]
Github didn't like my trying to update this PR, so I made a new one: https://github.com/felipenoris/XLSX.jl/pull/131

**Pull request closed without merging**
