### PR TITLE
Julia 0.7: fixed all errors and deprecations

### PR DESCRIPTION
**Pull request by zundertj**
This is not compatible with Julia 0.6; do you wish to support 0.6 and 0.7 simultaneously, or should the next release be Julia 0.7 only?

Ideally, we should get rid of the Nullables dependency as well

### CODE REVIEW

**Comment by felipenoris** [comment]
This is great!
I´m against supporting both 0.6 and 0.7 .  Support for 0.6 will be done in older releases.

**Comment by felipenoris** [comment]
How about the new iteration protocol?

**Comment by zundertj** [comment]
I've ported CellRange and ColumnRange, and it seems it makes code a bit easier. However, the other iterators are a bit more involved, so if you want to give it a try, feel free. 

Nullables and Compat deps have been removed.

**Comment by zundertj** [comment]
Okay, can you create one? Since I cannot; and thus cannot update the PR right now.

**Comment by felipenoris** [comment]
You're right. Just did that.

**Comment by zundertj** [comment]
Done

**Comment by felipenoris** [comment]
This is such a great work! Thank you!

**Pull request merged**
